### ISSUE TITLE
Provide example usage for other static site generatos

### ISSUE THREAD

**Issue by mre** [tinysearch/tinysearch#10]
We need to add some usage examples for 

* [ ] Jekyll
* [x] Hugo
* [ ] Cobalt

For the most part, this means showing how to create an `index.json` as shown in `/fixtures/index.json` from this repo.

For example, I'm using the following template file for [zola](https://www.getzola.org/):

```twig
{% set section = get_section(path="_index.md") %}

[
{%- for post in section.pages -%}
{
"title": {{ post.title | safe | striptags | json_encode }},
"url": {{ post.permalink | safe | json_encode }},
"body": {{ post.content | safe | striptags | json_encode }}
}{% if not loop.last %},{% endif %}
{%- endfor -%}
]
```

If someone wants to tackle this, feel free to add a comment here so that others know you're working on this. You can also create a pull request straight away.

**Comment by mre** [comment]
Jekyll example: https://learn.cloudcannon.com/jekyll/output-json/

**Comment by mre** [comment]
Thanks @Lusitaniae,
added your tutorial at https://github.com/mre/tinysearch/blob/master/howto/hugo.md.

**Comment by mre** [comment]
Anyone wants to tackle Jenkins or Pelican?

**Comment by lord-re** [comment]
To implement it in Hugo, you can have a simpler setup : 

layout/_default/list.json.json

> [
> {{ range $index , $e := .Site.RegularPages }}{{ if $index }}, {{end}}{{ dict "title" .Title "url" .Permalink "body" .Plain | jsonify }}{{end}}
> ]
> 

and config.toml

> [outputs]
>   home = ["html","json","rss"]

( if you only put json, you won't build your site and your rss anymore).

It's a bit simpler and doesn't break the site.

**Comment by mre** [comment]
Nice @lord-re. Much appreciated!
Can you edit the file [here](https://github.com/tinysearch/tinysearch/edit/master/howto/hugo.md) and create a pull request?
I'd merge it on the spot.

**Comment by Ninjani** [comment]
Hello! Figured this out for Pelican to add to our website.

You need a `templates/json.html` file with:
```html
[
{%- for article in articles -%}
{% if article.status != "draft" %}
{
"title": {{ article.title | striptags | tojson | safe }},
"url": {{ article.url | tojson | safe }},
"body": {{ article.content | striptags | tojson | safe }}
}{% if not loop.last %},{% endif %}
{% endif %}
{%- endfor -%}
]
```

and a `json.md` file in your `content/pages` folder with 
``` md
Title: JSON
Template: json
Slug: json
```
Then, after running `pelican content`, `tinysearch --path output output/pages/json.html` builds the index.

Shall I make a PR?

**Comment by mre** [comment]
Nice! PR would be very welcome. 😊

**Comment by dertuxmalwieder** [comment]
> To implement it in Hugo, you can have a simpler setup

Doing that generates a `public/index.json` which contains an empty list. Why?

**Comment by mre** [comment]
Sorry for the late response. I don't know what might cause this.
Maybe @lord-re has an idea. If so, please post below and we can reopen.
