### ISSUE TITLE
Make body field optional

### ISSUE THREAD

**Issue by Lusitaniae** [tinysearch/tinysearch#117]
Some bigger websites may have high number of pages to index.

Making the body field optional would make the index more manageable and performant at a bigger scale.

**Comment by felipe-fg** [comment]
Hey, @mre.

I'd like to try this issue for Hacktoberfest.

I was thinking about changing [this field](https://github.com/tinysearch/tinysearch/blob/master/bin/src/index.rs#L7) to `Option<String>` and then [filter here](https://github.com/tinysearch/tinysearch/blob/master/bin/src/storage.rs#L47) posts that contains a body content. That way, only title will be [added here](https://github.com/tinysearch/tinysearch/blob/master/bin/src/storage.rs#L73).
Is this a good approach?

Thank you.

**Comment by mre** [comment]
Yes, go for it. It's a good approach. 👍 Assigning to you @felipe-fg. Have fun.
