### ISSUE TITLE
Add an option to only generate the wasm

### ISSUE THREAD

**Issue by lord-re** [tinysearch/tinysearch#123]
Now, each time you invoke tinysearch it create many files :

  - package.json
  - tinysearch_engine_bg.d.ts
  - tinysearch_engine_bg.wasm
  - tinysearch_engine.d.ts
  - tinysearch_engine.js

Generating (or cleaning every files except the wasm) only the wasm could be nice to integrate this process in an automated publish workflow.

Maybe another way to see it would be to only create the wasm by default, and an option to also generate the js, demo.html…

**Comment by mre** [comment]
Good point! I like that idea. 
There could be a `tinysearch build`, which only builds the wasm and a `tinysearch init`, which initializes the project and generates the other files, too. 🤔

**Comment by mre** [comment]
This is mostly done now in `master` thanks to https://github.com/tinysearch/tinysearch/pull/168. Release soon. Apologies for the delay.
