### ISSUE TITLE
Consider replacing failure crate with anyhow or thiserror ?

### ISSUE THREAD

**Issue by vishalsodani** [tinysearch/tinysearch#126]
The author of `failure` himself says so here https://internals.rust-lang.org/t/failure-crate-maintenance/12087/3.

**Comment by mre** [comment]
Sure! Great idea. Would you like to do the migration and send me a pull request? Have a bit too much on my plate at the moment. 😅 🍝

**Comment by vishalsodani** [comment]
> Sure! Great idea. Would you like to do the migration and send me a pull request? Have a bit too much on my plate at the moment. sweat_smile spaghetti

Sure.

**Comment by mre** [comment]
Whoops, forgot to close this issue. Thanks for your work @vishalsodani. ⭐
