### ISSUE TITLE
Consider replacing structopt with argh crate ?

### ISSUE THREAD

**Issue by vishalsodani** [tinysearch/tinysearch#128]
This change will reduce the number of dependencies.

**Comment by mre** [comment]
Perfect. I'm all for it. 🏴‍☠️ Can you create a PR like last time? 😉

**Comment by vishalsodani** [comment]
@mre I have linked my attempt. One issue that I am facing is that I have to use --index as argument to make it work like this 
    `./target/debug/tinysearch --index fixtures/index.json`. 
But,
     `cargo run fixtures/index.json` does not work.

**Comment by mre** [comment]
It should be ```cargo run -- fixtures/index.json```
(Mind the `--`, which separates the cargo args from the tinysearch args)

**Comment by vishalsodani** [comment]
> It should be `cargo run -- fixtures/index.json`
> (Mind the `--`, which separates the cargo args from the tinysearch args)

Cool. So, this works `cargo run -- --index fixtures/index.json`

**Comment by mre** [comment]
Side-note, does argh support subcommands? E.g. `tinysearch build ...` and `tinysearch deploy ...`?
Considering to use something like that in the future.

**Comment by vishalsodani** [comment]
Yes, subcommands are supported.

**Comment by mre** [comment]
Change by @vishalsodani merged. Closing this now. 🎉
