### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by mre** [tinysearch/tinysearch#134]
Was thinking a lot about the project name lately.
I picked it, because it felt like an obvious name for a... tiny search.

Now I have my doubts:
* Not the the most creative of names.
* Is it tinysearch or tiny-search or tiny_search on crates.io?
* It's kinda tedious to type out. Shorter is better.

Was thinking of something short and snappy.
The two candidates I have in mind right now are **ty** (first and last letter of the current project name; a symbol for the project's tiny footprint) and **ivy** (can you tell I like the letter *y*?).
There is already a popular ivy project on Github [here](https://github.com/robpike/ivy), but it's in a super unrelated field, so I think it's fair game.
Open for other suggestions, too!

Would like to get an opinion from the other two core developers.
@jorgelbg, @fluential what's your take on this? Do you share my desire for a rename? 😆 
Everyone else is invited to discuss, too of course.

**Comment by fluential** [comment]
Well it depends if the goal is to be useful in a short way then shortest would be my pick. 

If it's just cosmetics choose whatever resonate with you the most, trust your inner guidance :)

**Comment by jorgelbg** [comment]
I was giving this a bit of thought to this and I was thinking on `tny` because it sounds like `tiny`/`teeny` but you save 1/2 characters in the process 🤔 also:  https://getyarn.io/yarn-clip/0be79837-c0e6-44ac-9dbd-13c69204ead1#j2yUtYzapeC.copy 😂

**Comment by mre** [comment]
I like it.

**Comment by fluential** [comment]
Sounds better yeah

**Comment by mzalevski** [comment]
imho `tny` > `ty` > `ivy` > `tinysearch`; `ty` is nice, but kinda awkward for me coz it means "you" in Polish :sweat_smile: maybe; also if we want the name to be truly tiny we could go with `tn` both i and y are vowels

**Comment by wparad** [comment]
Please don't make the name short to try to be funny. Descriptive names are so much better.

**Comment by mzalevski** [comment]
@wparad fair point, but there seems to some generic awkwardness to `tinysearch`. Maybe we could do better. On that note, maybe descriptive, but different, e.g. `bloom-search` as in "Writing a full-text search engine using Bloom filters" (the inspiration article for the project).

**Comment by mre** [comment]
> what's wrong with tinysearch?

@wparad I mentioned some reasons in the first comment.

>   * Not the the most creative of names.
>   * Is it tinysearch or tiny-search or tiny_search on crates.io?
>   * It's kinda tedious to type out. Shorter is better.

Especially the last two points are concerning me. 
Then again I'm not 100% convinced anymore that they warrant a rename. :/

**Comment by wparad** [comment]
> > what's wrong with tinysearch?
> 
> @wparad I mentioned some reasons in the first comment.
> 
> > * Not the the most creative of names.
> > * Is it tinysearch or tiny-search or tiny_search on crates.io?
> > * It's kinda tedious to type out. Shorter is better.
> 
> Especially the last two points are concerning me.
> Then again I'm not 100% convinced anymore that they warrant a rename. :/

Oh definitely :+1: for the rename and naming consistency, just don't call it `ty`. `search` seems like an important word to have, outside of that though, I don't have any good suggestions.

**Comment by kapilt** [comment]
Fwiw this was the top hit for me on a Google search for wasm website search

**Comment by ms-ati** [comment]
I would please keep the name `tinysearch`. It is searchable, recognizable, it says what it does, and there are already a lot of references to it.

**Comment by mre** [comment]
We haven't changed the name in two years and now it's probably too late. I was hesitating because as you said the `search` part is quite for SEO, haha. My favorite is still `tny`, though. 😉

**Comment by millette** [comment]
My two cents: the name is good as is.

**Comment by mre** [comment]
As of today, I no longer plan to rename the project. While I'm still not 100% happy with it, it's _fine_ and the project can easily be found, which is the main objective. Thanks y'all for the input!
