### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ibnishak** [tinysearch/tinysearch#147]
OS: ArchLinux
Tinysearch version: Tried 0.6.2 and 0.6.0

What I did
- Installed wasm-pack, terser, binaryen, and finally tinysearch
- copied the given example file to index.json
- ran the following variations of commands

```
tinysearch index.json
tinyseach "index.json"
tinesearch /absolute/path/to/index.json
```

All of them gave the following output

```
Unpacking tinysearch WASM engine into temporary directory "/tmp/.tmpk894cL"
Start unpack
Copying index into crate
Error: No such file or directory (os error 2)
```

Kindly advice as to what other info would be useful

**Comment by mre** [comment]
Huh, it looks like the engine is not statically included inside the tinysearch binary. Maybe I broke something during the last release... 🤔

**Comment by blackary** [comment]
Any updates on this?

**Comment by siuying** [comment]
@mre I saw same error messages when installing the cargo. When building from source, I see error message `Error: failed to run "wasm-pack"`, and later `Error: wasm32-unknown-unknown target not found`. After I install both I can use this copy of tinysearch, but if I reinstall tinysearch from cargo I'd still get the same error.

**Comment by expilo** [comment]
Same issue here.
OS: Ubuntu 21.10 
wasm-pack 0.10.1
tinysearch 0.6.2

**Comment by AlexMikhalev** [comment]
Bump:
```
./target/release/tinysearch fixtures/index.json
Unpacking tinysearch WASM engine into temporary directory "/tmp/.tmpZTOX8N"
Starting unpack
Copying "../engine/src/lib.rs"
Copying "../engine/Cargo.toml"
Copying "../shared/.gitignore"
Copying "../engine/.gitignore"
Copying "../shared/src/lib.rs"
Copying "../shared/Cargo.toml"
Copying index into crate
Error: Invalid cross-device link (os error 18)
```
tinysearch from master git log -1
```commit 64e96ccb138ab6cbb8bb480c5ddcd12b112beb51 (HEAD -> master, origin/master, origin/HEAD)
Author: Matthias <matthias-endler@gmx.net>
Date:   Thu Sep 9 13:30:31 2021 +0200

    Update FUNDING.yml
```

wasm-pack 0.10.1
Ubuntu 21.10 (PopOS!) 
binaryen is version (91-1) from apt.

**Comment by blakehawkins** [comment]
0.6.2 release is not working for me either, but current head of master branch works

I think that this fixed it:

https://github.com/tinysearch/tinysearch/compare/v0.6.2...master#diff-322926ac8e657483f4af4b17984587cd911be04cdf671ecf5aac209867992c06R93

@mre I recommend to make a new cargo release 0.6.3

**Comment by mre** [comment]
Oh! Sorry, I forgot to release 0.6.3 with the patch. Apologies.
Released [v0.6.3](https://github.com/tinysearch/tinysearch/releases/tag/v0.6.3) now. Also added some pre-built binaries to make installation a little easier and quicker. If anyone could test it and report back that would be very helpful. At least on my homepage it works with that version.

**Comment by blakehawkins** [comment]
0.6.3 is not working for me:

```
...
Starting unpack
Name: /home/blake/workspace/myproject/storage
Name: /home/blake/workspace/myproject/.gitignore
Name: /home/blake/workspace/myproject/.sass-cache
Name: /home/blake/workspace/myproject/docker-compose.yml
Name: /home/blake/workspace/myproject/README.md
Name: /home/blake/workspace/myproject/.git
Name: /home/blake/workspace/myproject/assets
Name: /home/blake/workspace/myproject/Gemfile.lock
Name: /home/blake/workspace/myproject/404.md
Name: /home/blake/workspace/myproject/Gemfile
Name: /home/blake/workspace/myproject/_config.yml
Name: /home/blake/workspace/myproject/.github
Name: /home/blake/workspace/myproject/_pages
Name: /home/blake/workspace/myproject/CNAME
Name: /home/blake/workspace/myproject/_layouts
Name: /home/blake/workspace/myproject/_sass
Name: /home/blake/workspace/myproject/index.md
Name: /home/blake/workspace/myproject/images
Name: /home/blake/workspace/myproject/tmp
Name: /home/blake/workspace/myproject/_site
Name: /home/blake/workspace/myproject/_includes
Error: Engine directory could not be created at /tmp/.tmpZGQ8M1/engine
```

Is it possible that the cargo publish release is missing this binary data? https://github.com/tinysearch/tinysearch/blob/4343d551eea25adedd1ddfb736c40dafc399f3dd/bin/build.rs#L7

I don't see any of https://github.com/tinysearch/tinysearch/blob/d58e8ff67f7a5abd02b4893d641f3d7983c6861d/bin/src/main.rs#L48

**Comment by mre** [comment]
Could be, yeah. Reading through the source code of `includedir`, it writes the output to an `out_file`:
https://github.com/tilpner/includedir/blob/6a81c906e233649af1acec9835fe0a034b9274e2/codegen/src/lib.rs#L118-L149
Limited time right now, but maybe this file has to be included somewhere to make it into the release build?

At least the pre-built binary seems to work for my blog:
https://github.com/mre/endler.dev/runs/4657973699?check_suite_focus=true#step:11:16

Same for 0.6.3 installed with `cargo install`:
https://github.com/mre/endler.dev/runs/4718539058?check_suite_focus=true#step:11:18

Can you try one of the pre-built binaries for comparison?
And if you have an idea where the binary data has to be added to make it work, that would also be greatly appreciated.

**Comment by mre** [comment]
This is where it fails for you:
https://github.com/tinysearch/tinysearch/blob/18b0dc5d86902ac5e3266ca1dfa6787e54666663/bin/src/main.rs#L93-L102

It tries to unpack the engine code and if that directory doesn't exist after that, it means there was an error.

So I wonder what's above 
```
...
Starting unpack
Name: /home/blake/workspace/myproject/storage
Name: /home/blake/workspace/myproject/.gitignore
...
```

in your output. This is where it unpacks the engine code and prints the path.
Is this running locally or inside Github Actions? If it's local, can you check that the path exists and looks fine? If not, is the directory writeable?

**Comment by Cokemonkey11** [comment]
@mre thanks for taking a look.

> So I wonder what's above

It's just:

```
Unpacking tinysearch WASM engine into temporary directory "/tmp/.tmp3fYKc5"
Starting unpack
Name: /home/blake/workspace/myproject/storage
...
```

> Is this running locally or inside Github Actions? 

Local.

> If it's local, can you check that the path exists and looks fine?

The temp directory doesn't exist, but /tmp/ is writeable:

```
$ file /tmp/
/tmp/: sticky, directory
$ file /tmp/.tmp3fYKc5/
/tmp/.tmp3fYKc5/: cannot open `/tmp/.tmp3fYKc5/' (No such file or directory)
$ [ -w /tmp/ ]
$ echo $?
0
```

The weird thing for me is still that there are none of these:

https://github.com/tinysearch/tinysearch/blob/d58e8ff67f7a5abd02b4893d641f3d7983c6861d/bin/src/main.rs#L48

**Comment by blakehawkins** [comment]
@mre thanks for taking a look.

> So I wonder what's above

It's just:

```
Unpacking tinysearch WASM engine into temporary directory "/tmp/.tmp3fYKc5"
Starting unpack
Name: /home/blake/workspace/myproject/storage
...
```

> Is this running locally or inside Github Actions? 

Local.

> If it's local, can you check that the path exists and looks fine?

The temp directory doesn't exist, but /tmp/ is writeable:

```
$ file /tmp/
/tmp/: sticky, directory
$ file /tmp/.tmp3fYKc5/
/tmp/.tmp3fYKc5/: cannot open `/tmp/.tmp3fYKc5/' (No such file or directory)
$ [ -w /tmp/ ]
$ echo $?
0
```

The weird thing for me is still that there are none of these:

https://github.com/tinysearch/tinysearch/blob/d58e8ff67f7a5abd02b4893d641f3d7983c6861d/bin/src/main.rs#L48

**Comment by keyneom** [comment]
I'm running into the same issue locally:
```Unpacking tinysearch WASM engine into temporary directory "/tmp/.tmpVHlnPa"
Starting unpack
Name: [absolute path]/public/search/tinysearch_engine.js
Name: [absolute path]/public/search/tinysearch_engine_bg.wasm
Error: Engine directory could not be created at /tmp/.tmpVHlnPa/engine```

**Comment by mre** [comment]
I created a pull request here: https://github.com/tinysearch/tinysearch/pull/154.
If someone could test this and report back I'd be very thankful.

**Comment by Jieiku** [comment]
I just tested from a fresh install today, no issues.

**Comment by mre** [comment]
Can you try again using `cargo install tinysearch`? I think that's what people have problems with.

**Comment by Jieiku** [comment]
Yes, I will spin up a new linux vm, then I can be sure there are not already any preinstalled tools/libraries.

I do not think I will have time today, works is keeping me too busy, can probably check it later tonight.

**Comment by Jieiku** [comment]
I am going to test this now.

**Comment by mre** [comment]
This is resolved now.

The reason why it broke was a limitation by cargo: it does not allow including one crate inside another one. This is done to avoid unwanted complexity and is a sane default. In our case, however, it leads to the situation that the engine crate was missing from the tinysearch crate on crates.io.
See also https://github.com/tinysearch/tinysearch/issues/170#issuecomment-1650709333.

The latest tinysearch 0.8.2 fixes this issue. Apologies for the long delay to produce a fix.
