### ISSUE TITLE
Too many false positives

### ISSUE THREAD

**Issue by expilo** [tinysearch/tinysearch#149]
I guess I have pushed capabilities of tinysearch to the limits. The site I'm indexing is by no means tiny. It's over 1700 pages albeit with very little text. The compiled wasm binary is 343k . Amazingly it still works very fast, though in case of some queries I'm getting a lot of false positives, like  over 50%. I was wondering if it might be possible to make it more precise at the cost of a larger binary. I could live up with a ca 1MB binary as this site definitely does not have to load under 3s. 
I was using the docker image to compile the binary. 

`docker run -v $PWD:/tmp tinysearch/cli index.json`

**Comment by mre** [comment]
Can you try to compile the version from `master`? We recently switched to XOR filters, which might give you a better false-positive rate. The Docker image is not updated to the newest version yet unfortunately.

**Comment by expilo** [comment]
I managed to compile but still the old error, which forced me to use docker image, persists. When I try tu run `tinysearch index.json` I'm getting only

Unpacking tinysearch WASM engine into temporary directory "/tmp/.tmppr7ORB"
Starting unpack
Copying "../engine/src/lib.rs"
Copying "../engine/Cargo.toml"
Copying "../shared/.gitignore"
Copying "../engine/.gitignore"
Copying "../shared/src/lib.rs"
Copying "../shared/Cargo.toml"
Copying index into crate
Error: Invalid cross-device link (os error 18)

**Comment by expilo** [comment]
I managed to compile the 0.6.3 version but it did not help. Still getting the same false positives as with version 0.6.2

**Comment by expilo** [comment]
As I wrote in the comment to #151 I was finally able to overcome this problem by compiling and running tinysearch in /tmp directory. The resulting wasm binary gives better search results although I am still getting false positives. Xorf crate has got a lot of other filters which give better false positives ratio. Would it be possible to implement them as well, or at least one of them and give user the choice which one to use?

**Comment by Jieiku** [comment]
@expilo how were you able to tell that the xorf crate gave you better ffalse positives ratio? did you implement it locally?

**Comment by Jieiku** [comment]
@expilo do you have a repo where the xorf crate is in use?

**Comment by Jieiku** [comment]
@expilo do you have a fork of tinysearch where the xorf crate is in use

**Comment by mre** [comment]
The xorf crate is already used in `master`:
https://github.com/tinysearch/tinysearch/blob/10c060bb5a496b699be33ad3108e1cb36760d308/engine/Cargo.toml#L22-L24

What @expilo probably meant is that the _other_ filters, which are part of the xorf crate, but which we don't use right now. The features are currently listed at the top of the [xorf `README.md`](https://github.com/ayazhafiz/xorf). I have not looked into that myself, so I can't say which one would be the most promising to try next.

**Comment by mre** [comment]
Original issue seems to be resolved; closing this to keep the issue tracker clean.
