### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shijunti19** [tinysearch/tinysearch#153]
let engine_dir = temp_dir.path().join("engine");
    if !engine_dir.exists() {
      fs::create_dir_all(&engine_dir)?;
    }
    if !engine_dir.exists() {
        for path in fs::read_dir(out_path)? {
            println!("Name: {}", path.unwrap().path().display())
        }
        bail!(
            "Engine directory could not be created at {}",
            engine_dir.display()
        );
    }

    println!("Copying index into crate");
    // fs::rename("storage", engine_dir.join("storage"))?;
    fs::copy("storage", engine_dir.join("storage"))?;

两个物理硬盘，不能使用 fs::rename

**Comment by mre** [comment]
Thanks @shijunti19,
can you create a pull request for that?
