### ISSUE TITLE
Update Cargo build for tinysearch

### ISSUE THREAD

**Issue by lspdrz** [tinysearch/tinysearch#155]
The ```tinysearch fixtures/index.json``` command in the "Usage" section of the readme isn't working. I think this is because the Cargo build for tinysearch hasn't been changed since the fix in this PR: https://github.com/tinysearch/tinysearch/pull/154.

When I ran the local project using ```cargo run fixtures/index.json```, the generation worked as expected.

**Comment by mre** [comment]
Old issue, but this should be resolved now in 0.8.1 if you want to try again.
