### ISSUE TITLE
Is there a way to return the page description or body in the results?

### ISSUE THREAD

**Issue by Jieiku** [tinysearch/tinysearch#159]
How difficult would it be to also return the page description in the results?

I have been implementing tinysearch into the [abridge zola theme](https://github.com/Jieiku/abridge).

here is a demo using tinysearch: https://jieiku.github.io/abridge-tinysearch/

here is the normal demo which is using elasticlunr (zola's default): https://abridge.netlify.app/

abridge tinysearch branch:  https://github.com/Jieiku/abridge/tree/tinysearch

Here is how elasticlunr looks:

![abridge-elasticlunr](https://user-images.githubusercontent.com/106644/182745558-eb7f172b-9400-482f-9939-fd01ccf500fe.gif)

I have [modified the tinysearch js example](https://github.com/Jieiku/abridge/blob/tinysearch/static/tinysearch.js) to more tightly integrate with abridge, so it looks VERY similar, but I don't have a description to go along with the title:

![abridge-tinysearch](https://user-images.githubusercontent.com/106644/182745853-2fdb18a3-8f85-4c34-8ed3-e855b0661057.gif)

**Comment by Jieiku** [comment]
I was reading over some issues such as https://github.com/tinysearch/tinysearch/commit/39dbaba2b7c56e04b329041d50be369b67324da4

apparently the body is in the json index, just not sure how to fetch it...

https://github.com/Jieiku/abridge/blob/dac0392b3c4f0f377029beefb03e11d576acca66/static/tinysearch.js#L54-L85

**Comment by mre** [comment]
Great progress so far. The problem is that tinysearch stores the body as a Bloomfilter (XOR filter to be precise), which allows you to query if a word is contained in an article or not but it never returns the full body. That's the trick that makes tinysearch so tiny.

That said, we could consider extending the tinysearch input format to also take an optional field for each article which would be returned verbatim on every match. 

So

```json
[
  {
    "title": "My awesome article"
    "url": "https://example.com/",
    "meta": "Short description; returned verbatim",
    "body": "This is the full article body..."
  }
]
```

Not sure about `meta` yet. Open for suggestions.

**Comment by Jieiku** [comment]
I am not sure how much it would kill the small size of tinysearch, but if it can be added as an optional field that would be great!

I am planning to fully implement tinysearch and stork so that they can be directly compared against one another, if they cannot all do the same thing then it is not really an apples to apples comparison.

For Tinysearch I can include the results with and without a returned body in the comparison.

**Comment by Jieiku** [comment]
If we used the short description then it would probably keep tinysearch small enough and still provide some more info in the results.

**Comment by mre** [comment]
The beauty of the optional field is that it's zero overhead: users don't pay for it if they don't use it. On top of that, if it gets used then a user can still decide what to put in there and how long the content may be, thus controlling the overhead.
Let's go with `meta` then. 👍

**Comment by ardeaf** [comment]
My workaround was to extract the slug from the url in js and then get whatever data i need from my posts once i have that. Is that too slow for you?

**Comment by Jieiku** [comment]
Hello @ardeaf

So you are building a description by having your javascript access the matching pages to pull that data? That would be a bit slower, maybe not by much. I would also be able to use the full body with the makeTeaser though which is nice.

Could you share your code for this solution? I am sure I could adapt it without much trouble.

**Comment by Jieiku** [comment]
The more I think about it, the more I think that a meta option is the better solution.

**Comment by ardeaf** [comment]
> So you are building a description by having your javascript access the matching pages to pull that data? That would be a bit slower, maybe not by much. I would also be able to use the full body with the makeTeaser though which is nice.

My page that has tinysearch on first load grabs all the metadata from all the posts I have on my website and puts it in a prop for the page. When tinysearch returns the results it just filters through and displays the matches in their own components.

Here is the entire page:

```
import { TextField } from '@mui/material';
import React, { ReactElement, useEffect, useState } from 'react';
import { Metadata, Post } from '../../src/types';
import { NextPageWithLayout } from '../_app';
import Layout from '../../components/Layout';
import { default as init, search } from '../../public/tinysearch/tinysearch_engine.js';
import { getAllPosts } from '../../src/api';
import LargePostCard from '../../components/LargePostCard';
import { Box } from '@mui/system';
import theme from '../../src/theme';

interface BlogProps {
  allPosts: Post[];
}

type Title = string;
type Url = string;
type SearchResults = [Title, Url][];

const Blog: NextPageWithLayout<BlogProps> = ({ allPosts }) => {
  const [term, setTerm] = useState('');
  const [results, setResults] = useState<Title[]>([]);
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setTerm(event.target.value);
  };
  useEffect(() => {
    // for race conditions.
    let ignore = false;
    fetch('/tinysearch/tinysearch_engine_bg.wasm').then(async (wasm) => {
      if (!ignore) {
        await init(wasm)
      }
    })
    return () => { ignore = true }
  }, []);
  useEffect(() => {
    if (term == '') {
      setResults(allPosts.map(p => p.metadata.title));
    } else {
      const pending: SearchResults = search(term, 5);
      setResults(pending.map(([title, url]) => title));
    }
  }, [term]);
  return (
    <>
      <TextField id="outlined-search" label="Search" type="search" placeholder={'Search for past posts'}
                 value={term}
                 onChange={handleChange} fullWidth inputProps={{ sx: { textAlign: 'center' } }}/>
      {results.map((title, i) => {
        const p = allPosts.find(p => p.metadata.title == title);
        return <Box key={i} sx={{ marginTop: theme.spacing(3) }}>
          <LargePostCard metadata={p!.metadata} slug={p!.slug}/>
          {i + 1 < results.length && <Box sx={{ marginBottom: theme.spacing(3) }}/>}
        </Box>;
      })}
    </>
  );
};

Blog.getLayout = (page: ReactElement) => {
  const metadata: Metadata = {
    author: 'Ardeaf',
    date: '2022-07-27',
    description: 'Search through all my previous posts here.',
    heroImage: '/words.jpg',
    tags: [],
    title: 'Blog'
  };
  return (
    <Layout metadata={metadata}>
      {page}
    </Layout>
  );
};

export async function getStaticProps () {
  const allPosts = (await getAllPosts(['slug', 'metadata'])).sort((a, b) => {
    return a.metadata! > b.metadata! ? -1 : 1;
  }).reverse();
  return {
    props: {
      allPosts
    }
  };
}

export default Blog;
```

**Comment by Jieiku** [comment]
Thanks for posting your solution ardeaf, so your BlogProps data is basically a second index.

Because I am using a static site generator, I would really prefer to build the index ahead of time with the rest of the site.
I am thinking I would like to use the optional meta field as discuessed.

@mre have you done any work yet with implementing the optional meta field?

I am now done with the preliminary work for both tinysearch and stork.

Tinysearch demo: https://jieiku.github.io/abridge-tinysearch/

Stork demo: https://jieiku.github.io/abridge-stork/

I think the next step is to get the meta field in place.

I am also thinking of implementing some other ones and then completing this: https://github.com/tinysearch/tinysearch/issues/136

**Comment by mre** [comment]
No work was done yet. Feel free to give it a try if you like. Thanks! 🙏

**Comment by Jieiku** [comment]
Thanks for the quick response, I will give it a try.

**Comment by Jieiku** [comment]
I am very new to rust, This seems to be a hashmap within a hashmap?

so a hashmap of `title : url` within a hashmap that is `title+url : body` (is my understanding correct?)

My thought is to switch from using a hashmap to a vec.

// prepares the files in the given directory to be consumed by the generator
pub fn prepare_posts(posts: Posts) -> HashMap<PostId, Option<String>> {
    let mut prepared: HashMap<PostId, Option<String>> = HashMap::new();
    for post in posts {
        debug!("Analyzing {}", post.url);
        prepared.insert((post.title, post.url), post.body);
    }
    prepared
}

Being new to rust I dont want to cause any performance issues if hashmap is a deliberate choice and there is a way to keep the hashmap when adding `post.meta`

**Comment by Jieiku** [comment]
I added the meta field (still need to make it optional): https://github.com/Jieiku/tinysearch/commit/587bc849ff109a520fd11dc55b2cb7270219eb64

Here is the changes I made for the zola macro:

```html
{%- macro from_section(section) -%}
{%- set section = get_section(path=section) -%}
{%- for post in section.pages -%}
{%- if not post.draft -%}
{
"title": {{ post.title | striptags | json_encode | safe }},
"url": {{ post.permalink | json_encode | safe }},
"meta": {% if post.summary %}
          {{- post.summary | markdown(inline=true) | striptags | truncate(length=125) | json_encode | safe }}
        {%- elif post.description %}
          {{- post.description | striptags | truncate(length=125) | json_encode | safe }}
        {%- elif post.content %}
          {{- post.content | striptags | truncate(length=125) | json_encode | safe }}
        {%- endif %},
"body": {{ post.content | striptags | json_encode | safe }}
}
{%- if not loop.last -%},{%- endif %}
{%- endif -%}
{%- endfor -%}
{%- if section.subsections -%}
,
{%- for subsection in section.subsections -%}
{{ self::from_section(section=subsection) }}
{%- endfor -%}
{%- endif -%}
{%- endmacro from_section -%}
```

It works great: https://jieiku.github.io/abridge-tinysearch/

![tinysearch-meta](https://user-images.githubusercontent.com/106644/183513372-2ce01f0c-9f18-43cb-9743-35c78a493fb9.gif)

**Comment by Jieiku** [comment]
What would you suggest for making the meta field optional? There are probably a few ways to go about it, such as if the field is missing then use an empty string, but being new to rust I am wondering what the best way would be.

I am researching and thinking of ideas, so I might come up with something on my own, but curious what you think.

**Comment by Jieiku** [comment]
I should have this finished shortly it seems making the field optional might be easier than I thought.

**Comment by mre** [comment]
@Jieiku, would you be interested in co-maintaining the project? I'd need some help with the release management and you have more than what it takes. It's probably not a lot of work either. Please reach out in case you'd be interested and I can add you to the repo.

**Comment by Jieiku** [comment]
Sure! Happy to help.

**Comment by mre** [comment]
@Jieiku your mail address keeps failing. Wanted to send you the crates.io credentials. Can you tell me your crates.io username so I can add you?

**Comment by Jieiku** [comment]
I did not realize crates.io was directly tied to github. I updated my email in github so it should work now.

**Comment by mre** [comment]
Invite to the repos sent
