### ISSUE TITLE
Github action

### ISSUE THREAD

**Issue by leonhfr** [tinysearch/tinysearch#162]
Hi! I'm using Github actions to build and deploy a website, and I thought it'd be cool to integrate tinysearch. I didn't find any github action to do that so I made one: https://github.com/marketplace/actions/tinysearch-action It's a simple wrapper of the docker image.

I use it in https://github.com/leonhfr/blog to build the wasm, though the search is still pending theme integration.

Just thought I'd put it here in case it's useful to someone. Thanks for the work!

**Comment by mre** [comment]
Wow, this is pretty nice. Great work!
If you like we can mention it in the `README.md`. Feel free to create a PR. 😉

**Comment by leonhfr** [comment]
Thanks! I created on in https://github.com/tinysearch/tinysearch/pull/163 😄
