### ISSUE TITLE
latest tinysearch, cargo install tinysearch not working.

### ISSUE THREAD

**Issue by Jieiku** [tinysearch/tinysearch#170]
I cannot install tinysearch 0.8.1 via cargo

You would assume this works, but it does not:
```
cargo install tinysearch
```

```
warning: none of the package's binaries are available for install using the selected features
  bin "tinysearch" requires the features: `bin`
Consider enabling some of the needed features by passing, e.g., `--features="bin"`
```

Instead you need to do this, but it does not work either:
```
cargo install tinysearch --features=bin
```

```
error: couldn't read /home/jieiku/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tinysearch-0.8.1/assets/crate/Cargo.toml: No such file or directory (os error 2)
 --> /home/jieiku/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tinysearch-0.8.1/src/bin/utils/assets.rs:1:37
  |
1 |   pub static CRATE_CARGO_TOML: &str = include_str!(concat!(
  |  _____________________________________^
2 | |     env!("CARGO_MANIFEST_DIR"),
3 | |     "/assets/crate/Cargo.toml"
4 | | ));
  | |__^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/jieiku/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tinysearch-0.8.1/assets/crate/src/lib.rs: No such file or directory (os error 2)
 --> /home/jieiku/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tinysearch-0.8.1/src/bin/utils/assets.rs:5:33
  |
5 |   pub static CRATE_LIB_RS: &str = include_str!(concat!(
  |  _________________________________^
6 | |     env!("CARGO_MANIFEST_DIR"),
7 | |     "/assets/crate/src/lib.rs"
8 | | ));
  | |__^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `tinysearch` (bin "tinysearch") due to 2 previous errors
error: failed to compile `tinysearch v0.8.1`, intermediate artifacts can be found at `/tmp/cargo-installZTcieL`
```

**Comment by mre** [comment]
Hum,

I'm not sure if we need the bin feature. Can't say why it was introduced. Maybe just to reduce compile-times? I can't see any other reason. If so, I'd opt for removing that, as it's a footgun. 

The `cargo install` error sounds like it can't find the crate content, that we include. 🤔 

The git build issue looks different. Looks like it can't find wasm-pack? Is it in your path and can you call it from the cli?
For what it's worth, the Docker image uses the same setup and it works. So maybe you can try that, too, with `make build-docker`. If it works, you might be able to get some inspiration from there. Also, it uses the latest version of wasm-pack and builds cleanly.

**Comment by Jieiku** [comment]
The git build issue is resolved, you guessed it!

When I did `cargo install wasm-pack` that was placed into `~/.cargo/bin` which was not yet on my path.

so I edited my `.zshrc` and `.bashrc` to include this:

`export PATH=$PATH:/home/jieiku/.cargo/bin`

not sure why it worked previously with the older version of wasm-pack... maybe back then I installed it another way, or they changed the installer.

So all that leaves now is the Crates install way.

**Comment by mre** [comment]
I released 0.8.1 with what I thought was a fix. It wasn't. It still doesn't include the assets crate. Maybe I still did something wrong in the Cargo.toml.

**Comment by Jieiku** [comment]
I did notice less errors.

**Comment by mre** [comment]
The reason why the `cargo install` is failing is because cargo doesn't allow me to include a crate within another one.
E.g. this doesn't work in our `Cargo.toml`:

```toml
include = ["src", "assets", "README.md"]
```

It only includes the `demo.html` and the `stopwords`:

```
└── package
    ├── tinysearch-0.8.1
    │   ├── Cargo.lock
    │   ├── Cargo.toml
    │   ├── Cargo.toml.orig
    │   ├── README.md
    │   ├── assets
    │   │   ├── demo.html
    │   │   └── stopwords
    │   └── src
    │       ├── bin
    │       └── lib.rs
    └── tinysearch-0.8.1.crate
```

However, if I remove the `Cargo.toml` from `assets/crate`, it works:

```
└── package
    ├── tinysearch-0.8.1
    │   ├── Cargo.lock
    │   ├── Cargo.toml
    │   ├── Cargo.toml.orig
    │   ├── README.md
    │   ├── assets
    │   │   ├── crate
    │   │   │   └── src
    │   │   │       └── lib.rs
    │   │   ├── demo.html
    │   │   └── stopwords
    │   └── src
    │       ├── bin
    │       │   ├── tinysearch.rs
    │       │   └── utils
    │       │       ├── assets.rs
    │       │       ├── index.rs
    │       │       ├── mod.rs
    │       │       └── storage.rs
    │       └── lib.rs
    └── tinysearch-0.8.1.crate
 ```

Not sure what to do about it.
Kinda want to avoid manually copying the `Cargo.toml` into the engine folder after the crate got extracted.

**Comment by mre** [comment]
This should work now with 0.8.2. Can you try again?
Workaround was pretty straightforward: https://github.com/tinysearch/tinysearch/commit/cbfbea94e02686696527f4232a89e144efb1af44

**Comment by Jieiku** [comment]
just got home, will give it a try now.

**Comment by Jieiku** [comment]
That seems to have worked, I was able to install tinysearch, then use tinysearch against a .json file to generate the wasm.

I have not tried testing the generated wasm as part of my website yet, but I am not seeing any errors.

**Comment by mre** [comment]
Great! Closing as resolved then. Feel free to reopen if testing the generated wasm fails.

**Comment by millette** [comment]
`tinysearch --optimize index.json` produced the error for me yestetrday with `v0.8.2`. I'm not used to rust much.

I was able to run `wasm-opt` separately by downloading binaryen and

```sh
binaryen-version_114/bin/wasm-opt -Oz -o tinysearch_engine_bg.wasm tinysearch_engine_bg.wasm
```

**Comment by mre** [comment]
Works for me. What was the error you received?

tinysearch just calls `wasm-opt`. Make sure it's in your `PATH`. E.g. this should work from your terminal:

```
> wasm-opt --version
wasm-opt version 111
```

If it doesn't, that means you need to add `wasm-opt` to your `PATH`. You can check where it is with `which wasm-opt`. The easiest way would probably be to move it `/usr/local/bin` or so.

If you got a different error, let me know. 😉

**Comment by millette** [comment]
@mre Thanks, that will do the trick. Somehow I expected everything to be bundled together.

**Comment by mre** [comment]
Ah, you got it.
