### ISSUE TITLE
On npm

### ISSUE THREAD

**Issue by millette** [tinysearch/tinysearch#173]
I was confused for a minute when I noticed https://www.npmjs.com/package/tinysearch was 3 years old but then I checked it 0.8.2 was released last week.

Would it be possible to update npm with a new version only to point out that it's not updated on npm anymore to avoid confusion and point back to cargo/rust or github directly. Thanks!

**Comment by mre** [comment]
Do we need to do anything here?
I can see two options:
* [ ] Release a new tinysearch version on npm. This might be work and I wonder if anyone wants to look into it.
* [ ] Remove the old npm package and close the issue.

**Comment by millette** [comment]
I'm not sure how weird it is to have a rust library on npm, so my choice would be to remove the old npm package to avoid a little bit of confusion. #15 mentionned npm but it wasn't a popular choice at the time. Last pr to publish to npm was #37 which didn't pan out.

If it's published to npm, I think it has to be integrated with the release so it's always up to date.

**Comment by mre** [comment]
Makes sense. There still seem to be some weekly downloads, so I decided to deprecate the package for now.
People will get a warning when they want to install the package. In the future, I will probably remove it.
