### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ZulTheDev** [tinysearch/tinysearch#174]
Guys, can anyone help me with this[Problem](https://github.com/tinysearch/tinysearch/files/12395304/installer.log)?
I can't seem to install pop normally.. :(
I use 32GB thumb drive to install this.
:(

**Comment by mre** [comment]
It looks like you're creating an issue for the wrong project. This repository is about tinysearch, a static search engine written in Rust. Feels like you were looking to install Pop OS? In that case, you'll have better chances at https://www.reddit.com/r/pop_os
