### ISSUE TITLE
Try Xor filter instead of Cuckoo filter

### ISSUE THREAD

**Issue by mre** [tinysearch/tinysearch#64]
For some use-cases, Xor filters are supposed to be [faster and smaller than Bloom and Cuckoo filters](https://arxiv.org/abs/1912.08258).
Recently, support for strings was added to the xorfilter Rust crate:
https://github.com/bnclabs/xorfilter/blob/master/tests/xorfilter.rs#L56
We should test that to see if they make our wasm binary smaller.

If someone wants to give this a shot, please write a short comment here.
I'd be happy to provide mentoring if needed.

**Comment by lemire** [comment]
> We should test that to see if they make our wasm binary smaller.

They should!!!

**Comment by mre** [comment]
Oh sweet. Hearing that from the author of XorFilters is very motivating. I'll put that on the shortlist for the next round of tests I'll do. Thanks for feedback!
(Big fan of your work here btw.)

**Comment by mre** [comment]
Xor filters are great!

20-25% smaller wasm size: The test index is 99kB now, 49kB gzipped, 40kB brotli.
(Keep in mind that this was already highly optimized before.)
@lemire fyi.

The version in `master` was ported to Xor filters now.
Closing this. 🥳
